#!/bin/csh

foreach mode ( TauMass \
               TauTo1Prong \
               TauToF1Nu \
               TauToHmHmHpNu \
               TauToHmHmHpNu-alu \
               TauToHmNu \
               TauToHmPizNu \
               TauToKmEtaNu \
               TauToKmKmKpNu \
               TauToKmKstarzNu \
               TauToKmNu \
               TauToKmPhiNu \
               TauToKmPizEtaNu \
               TauToKmPizKstarzNu \
               TauToKmPizNu \
               TauToKstarmEtaNu \
               TauToMmNumbarNu \
               TauToPimKmKpNu \
               TauToPimKmPipNu \
               TauToPimKzbEtaNu \
               TauToPimKzbNu \
               TauToPimNu \
               TauToPimPhiNu \
               TauToPimPimPipNu \
               TauToPimPizEtaNu \
               TauToPimPizKzbNu \
               TauToPimPizNu )
 cd ${mode}
 if (-f pdg_average.input) then
    make pdg | tee log/pdg_average.log
 endif
 if (-f average.input) then
    make | tee log/average.log
 endif
 cd -
end
 
